---
namespace: 'r_pufky'
name: 'arr'
version: '13.0.0'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Media retrieval services for ansible.
license_file: 'LICENSE'
tags:
  - 'media'
  - 'download'
  - 'usenet'
  - 'torrent'
  - 'nzb'
  - 'arr'
  - 'linux'
  - 'tools'
  - 'networking'
# Update all collections with dependency changes.
dependencies:
  'r_pufky.lib': '>=13.0.7,<14.0.0'
  'r_pufky.data': '>=3.0.4'
  'r_pufky.deb': '>=13.0.9,<14.0.0'
  'r_pufky.srv': '>=13.2.0,<14.0.0'
  'ansible.posix': '=2.1.0'
  'community.postgresql': '=4.1.0'

repository: 'https://github.com/r-pufky/ansible_collection_srv'
documentation: 'https://github.com/r-pufky/ansible_collection_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_srv'
issues: 'https://github.com/r-pufky/ansible_collection_srv/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - '*docs/*'  # Do not include development docs in release.
